obstacle_range: 1.0
raytrace_range: 1.0
footprint: [[-0.15, 0.1], [0.15, 0.1], [0.15, -0.1], [-0.15, -0.1]]
#robot_radius: 0.2
inflation_radius: 0.4
max_obstacle_height: 1.8
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: laser, marking: true, clearing: true, expected_update_rate: 0}
